# manually correct specific citation detail
- id: doi:10.1117/12.434501
  title: Noninvasive cerebral blood flow monitoring by a dye bolus method:separation of extra- and intracerebral absorption changes by frequency-domain spectroscopy

- id: doi:10.1117/12.500479
  title: Functional brain imaging by CW-NIRS coregistered by blood flow monitors
  date: 2003-10-15

- id: doi:10.1002/mrm.20067
  remove: true

- id: pubmed:40800793
  remove: true

- id: doi:10.1186/s13244-025-02153-9

- id: doi:10.1016/j.pscychresns.2024.111915

# manually provide all citation details (can be a new citation)
- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review